import React from 'react'

const iconNames = {
  account_balance_wallet: 'account_balance_wallet',
  add_home: 'add_home',
  apartment: 'apartment',
  apartment_rounded: 'apartment',
  analytics: 'analytics',
  arrow_back_rounded: 'arrow_back',
  arrow_forward_rounded: 'arrow_forward',
  arrow_outward_rounded: 'arrow_outward',
  bathtub: 'bathtub',
  bed: 'bed',
  badge_outlined: 'badge',
  business_center_outlined: 'business_center',
  call: 'call',
  call_outlined: 'call',
  cell_tower: 'cell_tower',
  chat_bubble: 'chat_bubble',
  chat_bubble_outline: 'chat_bubble_outline',
  chat_bubble_rounded: 'chat_bubble',
  check_circle: 'check_circle',
  chevron_right: 'chevron_right',
  chevron_right_rounded: 'chevron_right',
  cloud_upload: 'cloud_upload',
  dashboard_customize_rounded: 'dashboard_customize',
  delete_outline: 'delete_outline',
  description_outlined: 'description',
  edit_rounded: 'edit',
  email_outlined: 'email',
  favorite: 'favorite',
  favorite_border: 'favorite_border',
  favorite_rounded: 'favorite',
  fullscreen_rounded: 'fullscreen',
  gps_fixed: 'gps_fixed',
  help_outline_rounded: 'help_outline',
  home: 'home',
  home_rounded: 'home',
  home_work_outlined: 'home_work',
  info: 'info',
  language_rounded: 'language',
  lock_clock_rounded: 'lock_clock',
  list_alt_outlined: 'list_alt',
  location_city: 'location_city',
  location_on: 'location_on',
  location_on_outlined: 'location_on',
  location_pin: 'location_pin',
  login_rounded: 'login',
  logout: 'logout',
  logout_rounded: 'logout',
  mail: 'mail',
  map: 'map',
  map_rounded: 'map',
  mark_chat_unread: 'mark_chat_unread',
  my_location: 'my_location',
  near_me_outlined: 'near_me',
  notes_outlined: 'notes',
  notifications_none_rounded: 'notifications_none',
  payments: 'payments',
  pending_actions_rounded: 'pending_actions',
  perm_media_outlined: 'perm_media',
  person: 'person',
  person_outline: 'person_outline',
  person_rounded: 'person',
  phone_android: 'phone_android',
  phone_outlined: 'phone',
  photo_library_outlined: 'photo_library',
  place_outlined: 'place',
  privacy_tip: 'privacy_tip',
  privacy_tip_outlined: 'privacy_tip',
  real_estate_agent: 'real_estate_agent',
  receipt_long_rounded: 'receipt_long',
  savings: 'savings',
  save_rounded: 'save',
  search: 'search',
  search_rounded: 'search',
  search_off: 'search_off',
  send_rounded: 'send',
  schedule: 'schedule',
  share: 'share',
  square_foot: 'square_foot',
  square_foot_outlined: 'square_foot',
  star: 'star',
  storefront: 'storefront',
  storefront_rounded: 'storefront',
  straighten_outlined: 'straighten',
  support_agent: 'support_agent',
  title: 'title',
  travel_explore: 'travel_explore',
  trending_up_rounded: 'trending_up',
  verified: 'verified',
  verified_user_outlined: 'verified_user',
  visibility: 'visibility',
  visibility_off_outlined: 'visibility_off',
  visibility_outlined: 'visibility',
  visibility_rounded: 'visibility',
  workspace_premium: 'workspace_premium',
  workspace_premium_rounded: 'workspace_premium',
  zoom_in_map_rounded: 'zoom_in_map',
}

export default function Icon({name, className = '', ...props}) {
  const normalizedName = name?.replace(/_rounded$|_outlined$/g, '')
  const iconName = iconNames[name] || iconNames[normalizedName] || normalizedName || 'chevron_right'

  return (
    <span className={`material-symbol ${className}`} aria-hidden="true" {...props}>
      {iconName}
    </span>
  )
}
